import io
from typing import Optional
from PIL import Image
from google import genai
from google.genai import types

from config import GEMINI_API_KEY


class StudioImageService:
    """
    Service for generating studio-quality images using Google Gemini.
    This service only handles the image generation - business logic is in the controller.
    """

    @staticmethod
    def generate_studio_image(
        image_file,
        prompt: str
    ) -> dict:
        """
        Generate a studio-quality image using Gemini.

        Args:
            image_file: File-like object or PIL Image
            prompt: The prompt to use for generation

        Returns:
            Dict with success status and generated PIL Image object
        """
        try:
            client = genai.Client(api_key=GEMINI_API_KEY)

            # Open the image if it's a file-like object
            if isinstance(image_file, Image.Image):
                image = image_file
            else:
                image = Image.open(image_file)

            print(f"[STUDIO SERVICE] Generating image with Gemini...")
            print(f"[STUDIO SERVICE] Prompt: {prompt[:80]}...")

            # Generate the image
            response = client.models.generate_content(
                model="gemini-2.5-flash-image",
                contents=[prompt, image],
                config=types.GenerateContentConfig(
                    response_modalities=['Text', 'Image']
                )
            )

            # Process response
            generated_image = None
            text_response = None

            for part in response.candidates[0].content.parts:
                if part.text is not None:
                    text_response = part.text
                elif part.inline_data is not None:
                    generated_image = Image.open(io.BytesIO(part.inline_data.data))

            if generated_image is None:
                return {
                    "success": False,
                    "message": "No image generated by Gemini",
                    "text_response": text_response
                }

            print(f"[STUDIO SERVICE] Image generated successfully")

            return {
                "success": True,
                "image": generated_image,
                "text_response": text_response
            }

        except Exception as e:
            print(f"[STUDIO SERVICE] Error: {str(e)}")
            return {
                "success": False,
                "message": str(e)
            }
